%% staging script for segmenting washington task data
  
EEG.group = '';
fid = fopen('washington_participants.csv','r');
rline = fgetl(fid);
while ischar(rline);
    splitline = strsplit(rline,',');
    subj = splitline{1};
    if strcmp(EEG.subject(1),'p');
        EEG.group = 'pilot';
        break;
    end;
    if strcmp(EEG.subject(2:end),subj);
        risk = splitline{2};
	    outcome = splitline{3};
	    EEG.gender = splitline{4};
	    if strcmp(risk,'LRC');
            if strcmp(outcome,'no_asd');
	            EEG.group = 'LRC-';
            elseif strcmp(outcome,'asd');
	            EEG.group = 'LRC+';
            elseif strcmp(outcome,'no_asd_18m');
                EEG.group = 'LRC-_18m';
                %EEG.group = 'LRC-';
            elseif strcmp(outcome,'unknown');
                EEG.group = 'LRC_UNK';
            end;
	    elseif strcmp(outcome,'no_asd');
	        EEG.group = 'HRA-';
	    elseif strcmp(outcome,'no_asd_18m');
	        EEG.group = 'HRA-_18m';
            %EEG.group = 'HRA-';
        elseif strcmp(outcome,'asd');
	        EEG.group = 'HRA+';
        elseif strcmp(outcome,'asd_18m');
	        EEG.group = 'HRA+_18m';
            %EEG.group = 'HRA+';
        elseif strcmp(outcome,'unknown');
            EEG.group = 'HRA_UNK';         
	    end;
        break;
    end;
    rline = fgetl(fid);
end;
fclose(fid);
