% Input into eeg_init function is the three seperate task files for each participant
% Files that are being merged are from the same recording session
% Output from eeg_init is a single merged and initalized file for each participant

diary 'sourcedata/eeg/sub-s02.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_102_green002.raw', ...
          'sourcedata/eeg/ODS_102_red002.raw', ...
          'sourcedata/eeg/ODS_102_single002.raw'}, ...
          'sourcedata/eeg/sub-s02_task-ods_eeg.set');
         
diary 'sourcedata/eeg/sub-s03.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_103_green002.raw', ...
          'sourcedata/eeg/ODS_103_red002.raw', ...
          'sourcedata/eeg/ODS_103_single002.raw'}, ...
          'sourcedata/eeg/sub-s03_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s04.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_104_green002.raw', ...
          'sourcedata/eeg/ODS_104_red002.raw', ...
          'sourcedata/eeg/ODS_104_single002.raw'}, ...
          'sourcedata/eeg/sub-s04_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s05.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_105_green002.raw', ...
          'sourcedata/eeg/ODS_105_red002.raw', ...
          'sourcedata/eeg/ODS_105_single002.raw'}, ...
          'sourcedata/eeg/sub-s05_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s06.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_106_green002.raw', ...
          'sourcedata/eeg/ODS_106_red002.raw', ...
          'sourcedata/eeg/ODS_106_single002.raw'}, ...
          'sourcedata/eeg/sub-s06_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s07.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_107_green002.raw', ...
          'sourcedata/eeg/ODS_107_red002.raw', ...
          'sourcedata/eeg/ODS_107_single002.raw'}, ...
          'sourcedata/eeg/sub-s07_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s08.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_108_green002.raw', ...
          'sourcedata/eeg/ODS_108_red002.raw', ...
          'sourcedata/eeg/ODS_108_single002.raw'}, ...
          'sourcedata/eeg/sub-s08_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s09.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_109_green002.raw', ...
          'sourcedata/eeg/ODS_109_red002.raw', ...
          'sourcedata/eeg/ODS_109_single002.raw'}, ...
          'sourcedata/eeg/sub-s09_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s10.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_110_green002.raw', ...
          'sourcedata/eeg/ODS_110_red002.raw', ...
          'sourcedata/eeg/ODS_110_single002.raw'}, ...
          'sourcedata/eeg/sub-s10_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s11.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_111_green002.raw', ...
          'sourcedata/eeg/ODS_111_red002.raw', ...
          'sourcedata/eeg/ODS_111_single002.raw'}, ...
          'sourcedata/eeg/sub-s11_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s12.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_112_green002.raw', ...
          'sourcedata/eeg/ODS_112_red002.raw', ...
          'sourcedata/eeg/ODS_112_single002.raw'}, ...
          'sourcedata/eeg/sub-s12_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s13.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_113_green002.raw', ...
          'sourcedata/eeg/ODS_113_red002.raw', ...
          'sourcedata/eeg/ODS_113_single002.raw'}, ...
          'sourcedata/eeg/sub-s13_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s14.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_114_green002.raw', ...
          'sourcedata/eeg/ODS_114_red002.raw', ...
          'sourcedata/eeg/ODS_114_single002.raw'}, ...
          'sourcedata/eeg/sub-s14_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s15.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_115_green002.raw', ...
          'sourcedata/eeg/ODS_115_red002.raw', ...
          'sourcedata/eeg/ODS_115_single002.raw'}, ...
          'sourcedata/eeg/sub-s15_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s16.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_116_green002.raw', ...
          'sourcedata/eeg/ODS_116_red002.raw', ...
          'sourcedata/eeg/ODS_116_single002.raw'}, ...
          'sourcedata/eeg/sub-s16_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s17.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_117_green002.raw', ...
          'sourcedata/eeg/ODS_117_red002.raw', ...
          'sourcedata/eeg/ODS_117_single002.raw'}, ...
          'sourcedata/eeg/sub-s17_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s18.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_118_green002.raw', ...
          'sourcedata/eeg/ODS_118_red002.raw', ...
          'sourcedata/eeg/ODS_118_single002.raw'}, ...
          'sourcedata/eeg/sub-s18_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s19.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_119_green002.raw', ...
          'sourcedata/eeg/ODS_119_red002.raw', ...
          'sourcedata/eeg/ODS_119_single002.raw'}, ...
          'sourcedata/eeg/sub-s19_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s20.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_120_green002.raw', ...
          'sourcedata/eeg/ODS_120_red002.raw', ...
          'sourcedata/eeg/ODS_120_single002.raw'}, ...
          'sourcedata/eeg/sub-s20_task-ods_eeg.set');

diary 'sourcedata/eeg/sub-s21.log';
%% CHECK FOR OUTPUT PATH AND CRETAE IF NECESSARY
eeg_init({'sourcedata/eeg/ODS_121_green002.raw', ...
          'sourcedata/eeg/ODS_121_red002.raw', ...
          'sourcedata/eeg/ODS_121_single002.raw'}, ...
          'sourcedata/eeg/sub-s21_task-ods_eeg.set');

disp('Done!');
